services:
  bot:
    image: ghcr.io/pencelheimer/rusty-dlp-bot:latest
    restart: unless-stopped
    environment:
      TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
      RUST_LOG: ${RUST_LOG:-warn,rusty_dlp_bot=info}

      # Uncomment to enable cookie-based auth
      # YT_DLP_COOKIES: /cookies.txt
    # volumes:
    #   - /path/to/cookies.txt:/cookies.txt:ro
